name: Filewriter Example
on:
 workflow_dispatch:

jobs:
 files:
  runs-on: ubuntu-latest

  steps:
   - name: make directory
     run: mkdir testdir
   - name: make file
     run: echo korte tekst > testdir/testfile
   - name: validation
     run: ls testdir
