name: Issues Example

on:
 issues:
  type: [opened]
 
jobs:
 log-issue:
  runs-on: ubuntu-latest
  steps:
    - name: Log issue title
      run: echo ${{ github.event.issue.title }}
      
    - name: Log issue body
      run: echo ${{ github.event.issue.body }}
