name: Issues Example

on:
 issues:
  type: opened
 
jobs:
 show-issue:
  runs-on: ubuntu-latest
  steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number 
